# Quantanexus 配置默认值
quantanexus_version: "2.0.0"
quantanexus_cs_namespace: "quantanexus-cs"
quantanexus_cs_domain:  "{{ QN_CS_DOMAIN | default('cs1.quantanexus.com') }}"
quantanexus_mgr_namespace: "quantanexus-mgr"
quantanexus_helm_repository: "https://helm.hi168.com/charts"

# 镜像仓库配置
quantanexus_image_registry: "{{ IMAGE_REGISTRY }}"
quantanexus_use_http_ip: "{{ USE_HTTP_IP }}"
quantanexus_mgr_domain_ip: "{{ MGR_DOMAIN_IP }}"

# Quantanexus 组件配置
quantanexus_domain_name: "{{ QN_DOMAIN | default('mgr.quantanexus.com') }}"
quantanexus_cert_manager_issuer_name:  "{{ QN_CLUSTER_ISSUER | default('hwua-quantanexus') }}"
