- hosts: localhost
  gather_facts: no
  roles:
    - role: prometheus
    
- hosts: localhost
  gather_facts: no
  vars:
    CLUSTER_DIR: "{{ cluster_dir | default('/etc/kubeasz/cluster') }}"
  roles:
    - role: ingress-nginx

