{{- if and .Values.abcExperimentService.enabled .Values.abcExperimentService.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: abc-experiment-service
  namespace: {{ .Release.Namespace | default "quantanexus" }}
  labels:
    app: abc-experiment-service
    {{- include "quantanexus.labels" . | nindent 4 }}  
  annotations:
    {{- range $key, $value := .Values.abcExperimentService.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- include "quantanexus.labels" . | nindent 4 }}

spec:
  ingressClassName: {{ .Values.abcExperimentService.ingress.className }}
  rules:
    {{- if .Values.global.useHttpIP }}
    - host: null
    {{- end }}
    {{- if not .Values.global.useHttpIP }}
    - host: {{ include "quantanexus.domainName" . }}
    {{- end }}
      http:
        paths:
          {{- range .Values.abcExperimentService.ingress.paths }}
          - pathType: Prefix
            path: {{ . }}
            backend:
              service:
                name: abc-experiment-service
                port:
                  number: 8075
          {{- end }}
  {{- if and .Values.abcExperimentService.ingress.tls.enabled (not .Values.global.useHttpIP) }}
  tls:
    - hosts:
        - {{ include "quantanexus.domainName" . }}
      secretName: {{ .Values.abcExperimentService.ingress.tls.secretName }}
  {{- end }}
{{- end }}