---
- name: 添加 Harbor Helm 仓库
  kubernetes.core.helm_repository:
    name: hi168
    repo_url: https://helm.hi168.com/charts
    state: present


- name: 创建 values.yaml 配置文件
  template:
    src: values.yaml.j2
    dest: "/tmp/harbor-values.yaml"

- name: 创建 Harbor 命名空间
  kubernetes.core.k8s:
    name: harbor
    api_version: v1
    kind: Namespace
    state: present

- name: 部署Harbor
  kubernetes.core.helm:
    name: harbor
    chart_ref: hi168/harbor
    release_namespace: harbor
    chart_version: "{{ harbor_version }}"
    values_files:
      - "/tmp/harbor-values.yaml"
    state: present
    wait: true          # Helm 原生等待资源就绪
    wait_timeout: "3m"  # 3分钟，可按需调整