# ==========================
# MinIO 分布式集群配置
# ==========================

minio_chart_repo: "https://helm.hi168.com/charts"
minio_release: minio
minio_namespace: minio     
minio_s3_domain: "{{ QN_S3_DOMAIN | default('s3.qn.com') }}"
# 运行模式
minio_mode: distributed
cert_manager_cluster_issuer: "{{ QN_CLUSTER_ISSUER}}"
# 副本数（Pod 数量）
minio_replicas: 3
minio_storage_default_class: "longhorn"
# StatefulSet 级副本数（与上保持一致即可）
minio_statefulset_replica_count: 3

# 资源请求/限制
minio_resources_requests_memory: "1Gi"
minio_resources_limits_memory: "2Gi"

# 持久化
minio_persistence_size: "3Gi"

# Service 类型
minio_service_type: NodePort
minio_console_service_type: NodePort

# 镜像配置 - 新增部分
minio_image_registry: "{{ IMAGE_REGISTRY }}"

minio_image_repository: "quay.io-minio-minio"
minio_image_tag: "RELEASE.2024-12-18T13-15-44Z"
minio_mc_image_repository: "quay.io-minio-mc"
minio_mc_image_tag: "RELEASE.2024-11-21T17-21-54Z"

# 认证信息 - 新增部分
minio_root_user: "admin"
minio_root_password: "admin"

minio_ingress_enabled: true
# first bucket 
minio_create_juicefs_bucket: true
minio_juicefs_bucket_name: "juicefs-s3-public"
minio_juicefs_bucket_policy: "download"
