---
- name: 添加 GPU Operator Helm 仓库
  kubernetes.core.helm_repository:
    name: hi168
    repo_url: "{{ gpu_operator_helm_repository }}"
    state: present

- name: 创建 values.yaml 配置文件
  template:
    src: values.yaml.j2
    dest: "/tmp/gpu-operator-values.yaml"

- name: 创建 gpu-operator 命名空间
  kubernetes.core.k8s:
    name: gpu-operator
    api_version: v1
    kind: Namespace
    state: present

- name: 部署GPU Operator
  kubernetes.core.helm:
    name: gpu-operator
    chart_ref: hi168/gpu-operator
    release_namespace: gpu-operator
    chart_version: "{{ gpu_operator_version }}"
    values:
      driver.enabled: false
    values_files:
      - "/tmp/gpu-operator-values.yaml"
    state: present
    wait: true          
    wait_timeout: "5m"  # 5分钟，可按需调整