---
quantanexus_cs_version: "1.1.0"
quantanexus_helm_repository: "https://helm.hi168.com/charts"

quantanexus_cs_namespace: "quantanexus-cs"
quantanexus_clusster_issuer_name: "{{ QN_CLUSTER_ISSUER | default('hwua-quantanexus') }}" # 镜像仓库配置
quantanexus_cs_image_registry: "{{ IMAGE_REGISTRY }}"

# Quantanexus CS 组件配置
quantanexus_cs_service_namespace: "quantanexus-cs"
quantanexus_cs_domain_name:  "{{ QN_CS_DOMAIN | default('cs1.quantanexus.com') }}"
source_secret_ca_name: "root-ca-secret"
target_secret_ca_name: "root-ca-secret"


